blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/fabricio-entringer/linkedin-agent/discussions
    about: Ask questions and discuss with other community members
