name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check for syntax errors
      run: |
        echo "Checking for Python syntax errors..."
        python -m compileall ./app -f
        
    - name: Display Python and dependency versions
      run: |
        python --version
        pip list
        
    - name: Install development dependencies
      run: |
        pip install pytest pytest-cov flake8
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Verify imports work correctly
      run: |
        # Test that the main modules can be imported
        python -c "from app.tools.linkedin import LinkedInTool; from app.tools.browser import BrowserTool; from app.agents.linkedin_agent import LinkedInMessageCrew"
        
    - name: Verify ChromeDriver installation
      run: |
        # Install Chrome & ChromeDriver on the GitHub Actions runner
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())"
